export TW_DEFAULT_LANGUAGE="en"
export LC_ALL="C"
export ALLOW_MISSING_DEPENDENCIES=true

export OF_MAINTAINER=nguyenhung9xdev
export FOX_VERSION=$(date +%y.%m.%d)

export FOX_REPLACE_TOOLBOX_GETPROP=1
export FOX_USE_TAR_BINARY=1
export FOX_USE_SED_BINARY=1
export FOX_USE_BASH_SHELL=1
export FOX_ASH_IS_BASH=1
export FOX_ENABLE_APP_MANAGER=1

export FOX_USE_GREP_BINARY=1
export FOX_USE_XZ_UTILS=1

export FOX_USE_NANO_EDITOR=1
export OF_ENABLE_LPTOOLS=1

export OF_AB_DEVICE_WITH_RECOVERY_PARTITION=1
export FOX_RECOVERY_SYSTEM_PARTITION="/dev/block/mapper/system"
export FOX_RECOVERY_VENDOR_PARTITION="/dev/block/mapper/vendor"
export OF_USE_LZ4_COMPRESSION=1

export OF_FORCE_MAGISKBOOT_BOOT_PATCH_MIUI=1
export OF_DONT_PATCH_ENCRYPTED_DEVICE=1

export OF_NO_RELOAD_AFTER_DECRYPTION=1
export OF_NO_TREBLE_COMPATIBILITY_CHECK=1

export FOX_RESET_SETTINGS=disabled
export FOX_DELETE_AROMAFM=1

export OF_SCREEN_H=2400

export FOX_BUGGED_AOSP_ARB_WORKAROUND="1546300800"; # Tuesday, January 1, 2019 12:00:00 AM GMT+00:00

export OF_QUICK_BACKUP_LIST="/boot;/data;"

export OF_IGNORE_LOGICAL_MOUNT_ERRORS=1

export FOX_PATCH_VBMETA_FLAG=1

export FOX_VIRTUAL_AB_DEVICE=1

export OF_DYNAMIC_FULL_SIZE=9126805504

export OF_UNBIND_SDCARD_F2FS=1

export OF_SUPPORT_VBMETA_AVB2_PATCHING=1

export OF_FIX_DECRYPTION_ON_DATA_MEDIA=1
